#!/usr/bin/env bash

sudo pacman -S hyprland --needed --noconfirm

sudo pacman -S --noconfirm --needed hyprpaper
sudo pacman -S --noconfirm --needed wl-clipboard
sudo pacman -S --noconfirm --needed hyprshot
