#!/bin/bash

if pgrep -f gpu-screen-recorder > /dev/null; then
    pkill -SIGUSR1 -f gpu-screen-recorder
    notify-send "GPU Screen Recorder" "Clip saved!"
else
    notify-send "GPU Screen Recorder" "Not running"
fi
