#!/bin/bash

SAVE_DIR="$HOME/Videos/replays"
REPLAY_SECONDS=90
FPS=60
CONTAINER=mp4

mkdir -p "$SAVE_DIR"

if pgrep -f gpu-screen-recorder > /dev/null; then
    pkill -SIGINT -f gpu-screen-recorder
    notify-send "GPU Screen Recorder" "Stopped"
else
    WINDOW=$(hyprctl activewindow -j | jq -r '.class')
    gpu-screen-recorder -w "$WINDOW" -f $FPS -r $REPLAY_SECONDS -c $CONTAINER -o "$SAVE_DIR" &
    notify-send "GPU Screen Recorder" "Started: $WINDOW"
fi
